package org.bharath.enums;

public enum ConfigProperties {

    URL,
    BROWSER,
    OVERRIDEREPORTS,
    PASSEDSTEPSCREENSHOT,
    FAILEDSTEPSCREENSHOT,
    SKIPPEDSTEPSCREENSHOT,
    RETRYFAILEDTESTS,
    RUNMODE,
    SENDRESULTSTOELK,
    SELENIUMGRIDURL,
    ELASTICURL
}
