name: run amazon test in github actions

on: [ push,workflow_dispatch ]
jobs:
  run-web-test:
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:latest
        ports:
          - 4444:4444

      chrome-132:
        image: selenium/node-chrome:132.0-20250202
        options: >-
          --shm-size=2g
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: "4442"
          SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
          SE_OPTS: --disable-gpu --no-sandbox --disable-dev-shm-usage
#          --headless

      firefox-129:
        image: selenium/node-firefox:129.0-20250202
        options: >-
          --shm-size=2g
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: "4442"
          SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
          SE_OPTS: --headless

      chrome-123:
        image: selenium/node-chrome:123.0-20250202
        options: >-
          --shm-size=2g
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: "4442"
          SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
          SE_OPTS: --disable-gpu --no-sandbox --disable-dev-shm-
#

      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
        ports:
          - 9200:9200
        env:
          discovery.type: single-node
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
          xpack.security.enabled: "false"

      kibana:
        image: docker.elastic.co/kibana/kibana:8.17.1
        ports:
          - 5601:5601
        env:
          ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        continue-on-error: true
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Restore Maven packages
        id: cache-dependencies
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: ~/.m2/repository
          key: Linux-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            Linux-maven-

#      - name: Start selenoid
#        uses: Xotabu4/selenoid-github-action@v2
#        continue-on-error: true
#        with:
#          selenoid-start-arguments: |
#            --args "-timeout 60s"

      - name: Set up virtual display
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          echo "DISPLAY=:99"

      - name: Verify Xvfb
        run: |
          ps aux | grep Xvfb
          echo "DISPLAY=$DISPLAY"

      - name: Execute Automation Suite
        env:
          DISPLAY: :99
        timeout-minutes: 3
#        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        continue-on-error: false
        run: |
          mvn clean test -Djava.awt.headless=true -verbose
#          -Dtestng.dtd.http=true -verbose

      - name: Cache Save Maven packages
        if: success()
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: Linux-maven-${{ hashFiles('**/pom.xml') }}