name: run amazon test in github actions

on: [push,workflow_dispatch]
jobs:
  run-web-test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        continue-on-error: true
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Restore Maven packages
        id: cache-primes
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: prime-numbers
          key: ${{ runner.os }}-primes

      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
        continue-on-error: false
        with:
          selenoid-start-arguments: |
            --args "-timeout 60s"

      - name: setup chromedriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 132.0
          install-chromedriver: true

      - name: Execute Automation Suite
        if: steps.cache-primes.outputs.cache-hit != 'true'
        continue-on-error: false
        run: |
          mvn -B -Dmaven.test.failure.ignore=true clean test