name: run amazon test in github actions

on: [ push,workflow_dispatch ]
jobs:
  run-web-test:
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:latest
        ports:
          - 4444:4444

      chrome-132:
        image: selenium/node-chrome:132.0-20250202
        options: >-
          --shm-size=2g
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
        depends-on:
          - selenium-hub

      firefox-129:
        image: selenium/node-firefox:129.0-20250202
        options: >-
          --shm-size=2g
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
        depends-on:
          - selenium-hub

      chrome-123:
        image: selenium/node-chrome:123.0-20250202
        options: >-
          --shm-size=2g
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
        depends-on:
          - selenium-hub

      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
        ports:
          - 9200:9200
        env:
          discovery.type: single-node
          ES_JAVA_OPTS: -Xms512m -Xmx512m
          xpack.security.enabled: false

      kibana:
        image: docker.elastic.co/kibana/kibana:8.17.1
        ports:
          - 5601:5601
        env:
          ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        depends-on:
          - elasticsearch
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        continue-on-error: true
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Restore Maven packages
        id: cache-primes
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: prime-numbers
          key: ${{ runner.os }}-primes

      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
        continue-on-error: false
        with:
          selenoid-start-arguments: |
            --args "-timeout 60s"

      - name: Execute Automation Suite
        if: steps.cache-primes.outputs.cache-hit != 'true'
        continue-on-error: false
        run: |
          mvn -B clean test